###


POST http://localhost:8000/add_product
Content-Type: application/json

{
    "id":5,
    "name":"wow",
    "description":"wow",
    "price":45,
    "quantity":2
}


###

PUT http://localhost:8000/product
Content-Type: application/json

{
    "id":5,
    "name":"lll",
    "description":"ll",
    "price":45,
    "quantity":2
}



###

GET http://localhost:8000/product

###

DELETE http://localhost:8000/product/5